run-docker-compose:
	uv sync
	docker compose up --build

stop-docker-compose:
	docker compose down

clear-notebooks:
	find notebooks -name "*.ipynb" -exec jupyter nbconvert \
		--ClearOutputPreprocessor.enabled=True \
		--to notebook \
		--inplace {} \;
